### ISSUE TITLE
Multi-file images not correctly imported to OMERO

### ISSUE THREAD

**Issue by pwalczysko** [ome/ZarrReader#25]
Workflow:

1. Convert the ``...downloads.openmicroscopy.org/images/OME-TIFF/2016-06/binaryonly`` images into zarr using bf2raw version 0.4.0, using the command
2.  ``bioformats2raw binaryonly/multifile-Z1.ome.tiff multifile-Z1.ome.zarr``
3. Import the resulting ``multifile-Z1.ome.zarr`` folder to OMERO using the command (note the usage of the ``--depth 10``)
4. ``omero import --transfer=ln_s --skip=checksum --parallel-upload=10 --skip=minmax --depth 10 multifile-Z1.ome.zarr/``
5. Observe that the image in OMERO is consisting of 3 images with z=1 each https://merge-ci.openmicroscopy.org/web/webclient/?show=image-228865. This is not expected, as the result should be 1 image with 5 z planes, as shown in the ome.tiff import case https://merge-ci.openmicroscopy.org/web/webclient/?show=image-228823
6. log in as user-8 to the merge-ci to see the images

cc @joshmoore @sbesson

**Comment by joshmoore** [comment]
https://github.com/ome/ZarrReader/issues/25 was my first attempt at capturing the multi-image-ness. Not sure if it's yet specific enough for ZarrReader, @dgault. (It also doesn't try to capture the semantics when it's a non-bioformats2raw mix of groups)

**Comment by pwalczysko** [comment]
> #25 was my first attempt at capturing the multi-image-ness. Not sure if it's yet specific enough for ZarrReader, @dgault. (It also doesn't try to capture the semantics when it's a non-bioformats2raw mix of groups)

@joshmoore not sure why is your link above pointing to this very issue ? (#25)

**Comment by pwalczysko** [comment]
I think that this issue is solved now. The .zarr folder was inside another .zarr folder which probably confused the importer.
Now, with the adjustment described in https://github.com/ome/ZarrReader/issues/26#issuecomment-1091877301, the new import is indeed producing 1 image with 5 z planes as expected, see https://merge-ci.openmicroscopy.org/web/webclient/?show=image-228872

**Comment by pwalczysko** [comment]
Should I close this or is it still of relevance ?

**Comment by joshmoore** [comment]
I'd propose updating the title & description but leaving this open lest someone else get themselves into this same situation.

**Comment by NicoKiaru** [comment]
Yes so I think this issue is still valid, see linked thread above in the forum
